// TODO: Rendre plus dynamique l'intégration de nouvelles images

import photo1 from "./P1232212.jpg";
import photo2 from "./P1049668.jpg";
import photo3 from "./P1050348.jpg";
import photo4 from "./P1050420.jpg";
import photo5 from "./P1050468.jpg";
import photo6 from "./P1050604.jpg";
// import photo7 from "./P1083411.jpg";
// import photo8 from "./P1083443.jpg";
// import photo9 from "./P1083447.jpg";
// import photo10 from "./P1083782.jpg";
// import photo11 from "./P1083862.jpg";
import photo12 from "./P1094314.jpg";
import photo13 from "./P1106223.jpg";
import photo14 from "./P1106227.jpg";
import photo15 from "./P1128772.jpg";
import photo16 from "./P1128832.jpg";
import photo17 from "./P1128924.jpg";
import photo18 from "./P1139979.jpg";
import photo19 from "./P1140028.jpg";
import photo20 from "./P1151587.jpg";
import photo21 from "./P1151740.jpg";
import photo22 from "./P1175226.jpg";
// import photo23 from "./P1208181.jpg";
// import photo24 from "./P1208191.jpg";
import photo25 from "./IMG_6166.jpg";
import photo26 from "./IMG_6184.jpg";
import photo27 from "./P1013283.jpg";
import photo28 from "./P1037214.jpg";
import photo29 from "./P1037770.jpg";
import photo30 from "./P1038980.jpg";
import photo31 from "./P1038985.jpg";
import photo32 from "./P1308972.jpg";
import photo33 from "./P1309014.jpg";
import photo34 from "./ACP02559.jpg";
import photo35 from "./ACP02869.jpg";
import photo36 from "./ACP04100.jpg";
import photo37 from "./ACP01511.jpg";
import photo38 from "./ACP04176.jpg";
import photo39 from "./ACP04572.jpg";
import photo40 from "./ACP06853.jpg";
import photo41 from "./ACP06976.jpg";
import photo42 from "./ACP07254.jpg";
import photo43 from "./P1037796.jpg";
import photo44 from "./P1174927.jpg";
import photo45 from "./ACP00744.jpg";
import photo46 from "./ACP01313.jpg";
import photo47 from "./ACP01416.jpg";
import photo48 from "./ACP02690.jpg";
import photo49 from "./ACP03632.jpg";
import photo50 from "./ACP03636.jpg";
import photo51 from "./ACP04227.jpg";
import photo52 from "./ACP04230.jpg";
import photo53 from "./ACP07749.jpg";
import photo54 from "./ACP08184.jpg";
import photo55 from "./ACP09066.jpg";
import photo56 from "./DJI_0110.jpg";
import photo57 from "./DJI_0142.jpg";
import photo58 from "./DSC05138.jpg";
import photo59 from "./ACP00003.jpg";
import photo60 from "./ACP00026.jpg";
import photo61 from "./ACP00466.jpg";
import photo62 from "./ACP00632.jpg";
import photo63 from "./ACP01968.jpg";
import photo64 from "./ACP02007.jpg";
import photo65 from "./ACP03324.jpg";
import photo66 from "./ACP03462.jpg";
import photo67 from "./ACP03603.jpg";
import photo68 from "./ACP03710.jpg";
import photo69 from "./ACP04395.jpg";
import photo70 from "./ACP04446.jpg";
import photo71 from "./ACP04544.jpg";
import photo72 from "./ACP04803.jpg";
import photo73 from "./ACP04826.jpg";
import photo74 from "./ACP05709.jpg";
import photo75 from "./ACP06080.jpg";
import photo76 from "./ACP06204.jpg";
import photo77 from "./ACP06210.jpg";
import photo78 from "./ACP08267.jpg";
import photo79 from "./ACP09404.jpg";
import photo80 from "./ACP09453.jpg";
import photo81 from "./ACP09503.jpg";
import photo82 from "./ACP09749.jpg";
import photo83 from "./ACP09851.jpg";
import photo84 from "./ACP09938.jpg";
import photo85 from "./ACP09967.jpg";
import photo86 from "./ACP09973.jpg";
import photo87 from "./DJI_0280.jpg";
import photo88 from "./DJI_0290.jpg";
import photo89 from "./DSC04899.jpg";
import photo90 from "./DSC05012.jpg";
import photo91 from "./DSC05941.jpg";
import photo92 from "./DSC05958.jpg";
import photo93 from "./DSC05969.jpg";

const gallery = [
	{
		id: 1,
		src: photo1,
		location: "Seefelder Spitze, Autriche",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-05-27"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 2,
		src: photo2,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-07"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 3,
		src: photo3,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 4,
		src: photo4,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 5,
		src: photo5,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 6,
		src: photo6,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	// {
	// 	id: 7,
	// 	src: photo7,
	// 	location: "Mont Ouareau, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-06"),
	// 	width: 1920,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 8,
	// 	src: photo8,
	// 	location: "Mont Ouareau, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-06"),
	// 	width: 1440,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 9,
	// 	src: photo9,
	// 	location: "Mont Ouareau, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-06"),
	// 	width: 1440,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 10,
	// 	src: photo10,
	// 	location: "Saint-Hippolyte, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-13"),
	// 	width: 1512,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 11,
	// 	src: photo11,
	// 	location: "Saint-Hippolyte, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-13"),
	// 	width: 1440,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	{
		id: 12,
		src: photo12,
		location: "Saint-Hippolyte, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-11-13"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 13,
		src: photo13,
		location: "Zero Latency Montréal",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-12-16"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 14,
		src: photo14,
		location: "Zero Latency Montréal",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-12-16"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 15,
		src: photo15,
		location: "Joliette, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-02-20"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 16,
		src: photo16,
		location: "Joliette, Québec, Canada",
		title: null,
		description: "Entrée au concours « Joliette en hiver » en 2022",
		links: {
			html: null,
		},
		date: new Date("2022-02-20"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 17,
		src: photo17,
		location: "Joliette, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-02-20"),
		width: 1080,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 18,
		src: photo18,
		location: "Saint-Lin-Laurentides, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-02-27"),
		width: 1920,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 19,
		src: photo19,
		location: "Mascouche, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-03-04"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 20,
		src: photo20,
		location: "Dirty Dogs Saint-Laurent",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-03-26"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 21,
		src: photo21,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-04-10"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 22,
		src: photo22,
		location: "Saint-Lin-Laurentides, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-05-11"),
		width: 1920,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	

	{
		id: 25,
		src: photo25,
		location: "Centre Bell",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-06-24"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 26,
		src: photo26,
		location: "Centre Bell",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-06-24"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 27,
		src: photo27,
		location: "Montagne Blanche",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-07-03"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 28,
		src: photo28,
		location: "Sainte-Thérèse, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-04"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 29,
		src: photo29,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-06"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 30,
		src: photo30,
		location: "Terrebonne, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-17"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 31,
		src: photo31,
		location: "Terrebonne, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-17"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 32,
		src: photo32,
		location: "Réserve faunique La Vérendrye",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-08-26"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 33,
		src: photo33,
		location: "Réserve faunique La Vérendrye",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-08-26"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 34,
		src: photo34,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 35,
		src: photo35,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 36,
		src: photo36,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 37,
		src: photo37,
		location: "Bloc Shop Hochelaga",
		title: "Bloc-Hop 2022",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-10-29"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 38,
		src: photo38,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 39,
		src: photo39,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-20"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 40,
		src: photo40,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-10-02"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 41,
		src: photo41,
		location: "Cabane à Sucre Oswald, Saint-Esprit",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-02-04"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 42,
		src: photo42,
		location: "Cabane à Sucre Oswald, Saint-Esprit",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-02-04"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 43,
		src: photo43,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-06"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 44,
		src: photo44,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-05-07"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 45,
		src: photo45,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-03"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["produit"],
	},
	{
		id: 46,
		src: photo46,
		location: "Montréal, Québec, Canada",
		title: "Yatai MTL",
		description: "Montreal Shamisen Project",
		links: {
			html: null,
		},
		date: new Date("2023-06-12"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["evenement"],
	},
	{
		id: 47,
		src: photo47,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-19"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 48,
		src: photo48,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-11-20"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["urbain"],
	},
	{
		id: 49,
		src: photo49,
		location: "High Peaks Wilderness, NY, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-07-30"),
		width: 1920,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 50,
		src: photo50,
		location: "High Peaks Wilderness, NY, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-07-30"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 51,
		src: photo51,
		location: "Lac-Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-05"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 52,
		src: photo52,
		location: "Lac-Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-05"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 53,
		src: photo53,
		location: "Kinadapt",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-06"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["animal"],
	},
	{
		id: 54,
		src: photo54,
		location: "Kinadapt",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-06"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 55,
		src: photo55,
		location: "Sunrise, FL, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-14"),
		width: 1530,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait", "sport"],
	},
	{
		id: 56,
		src: photo56,
		location: "Peanut Island, FL, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-14"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage", "drone"],
	},
	{
		id: 57,
		src: photo57,
		location: "Montréal, Québec, Canada",
		title: "Yatai MTL",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-11"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["evenement", "drone", "urbain"],
	},
	{
		id: 58,
		src: photo58,
		location: "Montréal, Québec, Canada",
		title: "Yatai MTL",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-10"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["evenement", "animal", "portrait"],
	},
	{
		id: 59,
		src: photo59,
		location: "Longueuil, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-07-07"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["skateboard", "sport"],
	},
	{
		id: 60,
		src: photo60,
		location: "Montréal, Québec, Canada",
		title: "Troisième",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-05-18"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["skateboard", "sport"],
	},
	{
		id: 61,
		src: photo61,
		location: "Montréal, Québec, Canada",
		title: "Montreal Skates",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-07-20"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["skateboard", "sport"],
	},
	{
		id: 62,
		src: photo62,
		location: "Drummondville, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-08-11"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait", "animal"],
	},
	{
		id: 63,
		src: photo63,
		location: "Montréal, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-09-22"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["skateboard", "sport"],
	},
	{
		id: 64,
		src: photo64,
		location: "Montréal, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-09-22"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["skateboard", "sport"],
	},
	{
		id: 65,
		src: photo65,
		location: "Montréal, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-07-16"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["architecture"],
	},
	{
		id: 66,
		src: photo66,
		location: "Montréal, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-10-26"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait", "film", "bnw"],
	},
	{
		id: 67,
		src: photo67,
		location: "Montréal, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-10-30"),
		width: 936,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["architecture", "film", "bnw"],
	},
	{
		id: 68,
		src: photo68,
		location: "Sherbrooke, Québec, Canada",
		title: "Troisième x Bravad",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-11-01"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 69,
		src: photo69,
		location: "Montréal, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-13"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["concert"],
	},
	{
		id: 70,
		src: photo70,
		location: "Montréal, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-13"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["architecture"],
	},
	{
		id: 71,
		src: photo71,
		location: "Réserve faunique La Vérendrye",
		title: "Canot-camping",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-18"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["outdoors"],
	},
	{
		id: 72,
		src: photo72,
		location: "Réserve faunique La Vérendrye",
		title: "Canot-camping",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-19"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["outdoors"],
	},
	{
		id: 73,
		src: photo73,
		location: "Réserve faunique La Vérendrye",
		title: "Canot-camping",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-19"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["outdoors"],
	},
	{
		id: 74,
		src: photo74,
		location: "Rawdon, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-27"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["macro"],
	},
	{
		id: 75,
		src: photo75,
		location: "Rawdon, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-27"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 76,
		src: photo76,
		location: "Rawdon, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-27"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 77,
		src: photo77,
		location: "Rawdon, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-27"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 78,
		src: photo78,
		location: "",
		title: "Éclipse solaire totale 2024",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-04-08"),
		width: 1080,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["astro"],
	},
	{
		id: 79,
		src: photo79,
		location: "Montréal, Québec, Canada",
		title: "Okoso bags",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-06-12"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["produit", "skateboard"],
	},
	{
		id: 80,
		src: photo80,
		location: "Montréal, Québec, Canada",
		title: "Okoso bags",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-06-12"),
		width: 608,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["produit", "skateboard"],
	},
	{
		id: 81,
		src: photo81,
		location: "Montréal, Québec, Canada",
		title: "Okoso bags",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-06-12"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["produit", "skateboard"],
	},
	{
		id: 82,
		src: photo82,
		location: "Montréal, Québec, Canada",
		title: "Montreal Skates",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-06-12"),
		width: 1080,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["produit", "skateboard"],
	},
	{
		id: 83,
		src: photo83,
		location: "Montréal, Québec, Canada",
		title: "Troisième",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-05-18"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 84,
		src: photo84,
		location: "Montréal, Québec, Canada",
		title: "Troisième",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-05-18"),
		width: 1512,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 85,
		src: photo85,
		location: "Montréal, Québec, Canada",
		title: "Troisième",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-05-18"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 86,
		src: photo86,
		location: "Montréal, Québec, Canada",
		title: "Troisième",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-05-18"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 87,
		src: photo87,
		location: "",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-19"),
		width: 1350,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["drone", "camping"],
	},
	{
		id: 88,
		src: photo88,
		location: "",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-19"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["drone", "camping"],
	},
	{
		id: 89,
		src: photo89,
		location: "Montréal, Québec, Canada",
		title: "Troisième",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-05-18"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 90,
		src: photo90,
		location: "Montréal, Québec, Canada",
		title: "Troisième",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-05-18"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 91,
		src: photo91,
		location: "Saint-Lazare, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-06-11"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait", "animal"],
	},
	{
		id: 92,
		src: photo92,
		location: "Saint-Lazare, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-06-11"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait", "animal"],
	},
	{
		id: 93,
		src: photo93,
		location: "Saint-Lazare, Québec, Canada",
		title: "",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2024-06-11"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait", "animal"],
	},
];

export { gallery };
