// TODO: Rendre plus dynamique l'intégration de nouvelles images

import photo1 from "./P1232212.jpg";
import photo2 from "./P1049668.jpg";
import photo3 from "./P1050348.jpg";
import photo4 from "./P1050420.jpg";
import photo5 from "./P1050468.jpg";
import photo6 from "./P1050604.jpg";
// import photo7 from "./P1083411.jpg";
// import photo8 from "./P1083443.jpg";
// import photo9 from "./P1083447.jpg";
// import photo10 from "./P1083782.jpg";
// import photo11 from "./P1083862.jpg";
import photo12 from "./P1094314.jpg";
import photo13 from "./P1106223.jpg";
import photo14 from "./P1106227.jpg";
import photo15 from "./P1128772.jpg";
import photo16 from "./P1128832.jpg";
import photo17 from "./P1128924.jpg";
import photo18 from "./P1139979.jpg";
import photo19 from "./P1140028.jpg";
import photo20 from "./P1151587.jpg";
import photo21 from "./P1151740.jpg";
import photo22 from "./P1175226.jpg";
// import photo23 from "./P1208181.jpg";
// import photo24 from "./P1208191.jpg";
import photo25 from "./IMG_6166.jpg";
import photo26 from "./IMG_6184.jpg";
import photo27 from "./P1013283.jpg";
import photo28 from "./P1037214.jpg";
import photo29 from "./P1037770.jpg";
import photo30 from "./P1038980.jpg";
import photo31 from "./P1038985.jpg";
import photo32 from "./P1308972.jpg";
import photo33 from "./P1309014.jpg";
import photo34 from "./ACP02559.jpg";
import photo35 from "./ACP02869.jpg";
import photo36 from "./ACP04100.jpg";
import photo37 from "./ACP01511.jpg";
import photo38 from "./ACP04176.jpg";
import photo39 from "./ACP04572.jpg";
import photo40 from "./ACP06853.jpg";
import photo41 from "./ACP06976.jpg";
import photo42 from "./ACP07254.jpg";
import photo43 from "./P1037796.jpg";
import photo44 from "./P1174927.jpg";
import photo45 from "./ACP00744.jpg";
import photo46 from "./ACP01313.jpg";
import photo47 from "./ACP01416.jpg";
import photo48 from "./ACP02690.jpg";
import photo49 from "./ACP03632.jpg";
import photo50 from "./ACP03636.jpg";
import photo51 from "./ACP04227.jpg";
import photo52 from "./ACP04230.jpg";
import photo53 from "./ACP07749.jpg";
import photo54 from "./ACP08184.jpg";
import photo55 from "./ACP09066.jpg";
import photo56 from "./DJI_0110.jpg";
import photo57 from "./DJI_0142.jpg";
import photo58 from "./DSC05138.jpg";

const gallery = [
	{
		id: 1,
		src: photo1,
		location: "Seefelder Spitze, Autriche",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-05-27"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 2,
		src: photo2,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-07"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 3,
		src: photo3,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 4,
		src: photo4,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 5,
		src: photo5,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 6,
		src: photo6,
		location: "Baie Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-10-08"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	// {
	// 	id: 7,
	// 	src: photo7,
	// 	location: "Mont Ouareau, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-06"),
	// 	width: 1920,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 8,
	// 	src: photo8,
	// 	location: "Mont Ouareau, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-06"),
	// 	width: 1440,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 9,
	// 	src: photo9,
	// 	location: "Mont Ouareau, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-06"),
	// 	width: 1440,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 10,
	// 	src: photo10,
	// 	location: "Saint-Hippolyte, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-13"),
	// 	width: 1512,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 11,
	// 	src: photo11,
	// 	location: "Saint-Hippolyte, Québec, Canada",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2021-11-13"),
	// 	width: 1440,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	{
		id: 12,
		src: photo12,
		location: "Saint-Hippolyte, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-11-13"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 13,
		src: photo13,
		location: "Zero Latency Montréal",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-12-16"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 14,
		src: photo14,
		location: "Zero Latency Montréal",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-12-16"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 15,
		src: photo15,
		location: "Joliette, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-02-20"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 16,
		src: photo16,
		location: "Joliette, Québec, Canada",
		title: null,
		description: "Entrée au concours « Joliette en hiver » en 2022",
		links: {
			html: null,
		},
		date: new Date("2022-02-20"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 17,
		src: photo17,
		location: "Joliette, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-02-20"),
		width: 1080,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 18,
		src: photo18,
		location: "Saint-Lin-Laurentides, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-02-27"),
		width: 1920,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 19,
		src: photo19,
		location: "Mascouche, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-03-04"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 20,
		src: photo20,
		location: "Dirty Dogs Saint-Laurent",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-03-26"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 21,
		src: photo21,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-04-10"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 22,
		src: photo22,
		location: "Saint-Lin-Laurentides, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-05-11"),
		width: 1920,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	// {
	// 	id: 23,
	// 	src: photo23,
	// 	location: "Toscane, Italie",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2022-05-20"),
	// 	width: 1920,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	// {
	// 	id: 24,
	// 	src: photo24,
	// 	location: "San Quirico d'Orcia, Sienne, Italie",
	// 	title: null,
	// 	description: null,
	// 	links: {
	// 		html: null,
	// 	},
	// 	date: new Date("2022-05-20"),
	// 	width: 1440,
	// 	height: 1080,
	// 	color: "var(--dark)",
	// 	alt: null,
	// 	categories: [],
	// },
	{
		id: 25,
		src: photo25,
		location: "Centre Bell",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-06-24"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 26,
		src: photo26,
		location: "Centre Bell",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-06-24"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 27,
		src: photo27,
		location: "Montagne Blanche",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-07-03"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 28,
		src: photo28,
		location: "Sainte-Thérèse, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-04"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 29,
		src: photo29,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-06"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 30,
		src: photo30,
		location: "Terrebonne, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-17"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 31,
		src: photo31,
		location: "Terrebonne, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-17"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 32,
		src: photo32,
		location: "Réserve faunique La Vérendrye",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-08-26"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 33,
		src: photo33,
		location: "Réserve faunique La Vérendrye",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-08-26"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 34,
		src: photo34,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 35,
		src: photo35,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 36,
		src: photo36,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 37,
		src: photo37,
		location: "Bloc Shop Hochelaga",
		title: "Bloc-Hop 2022",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-10-29"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 38,
		src: photo38,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-17"),
		width: 2000,
		height: 1333,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 39,
		src: photo39,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-09-20"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 40,
		src: photo40,
		location: "Kinadapt, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-10-02"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 41,
		src: photo41,
		location: "Cabane à Sucre Oswald, Saint-Esprit",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-02-04"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 42,
		src: photo42,
		location: "Cabane à Sucre Oswald, Saint-Esprit",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-02-04"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 43,
		src: photo43,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2021-09-06"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 44,
		src: photo44,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-05-07"),
		width: 810,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 45,
		src: photo45,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-03"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["produit"],
	},
	{
		id: 46,
		src: photo46,
		location: "Montréal, Québec, Canada",
		title: "Yatai MTL",
		description: "Montreal Shamisen Project",
		links: {
			html: null,
		},
		date: new Date("2023-06-12"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["evenement"],
	},
	{
		id: 47,
		src: photo47,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-19"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: [],
	},
	{
		id: 48,
		src: photo48,
		location: "Montréal, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2022-11-20"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["urbain"],
	},
	{
		id: 49,
		src: photo49,
		location: "High Peaks Wilderness, NY, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-07-30"),
		width: 1920,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 50,
		src: photo50,
		location: "High Peaks Wilderness, NY, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-07-30"),
		width: 864,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 51,
		src: photo51,
		location: "Lac-Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-05"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 52,
		src: photo52,
		location: "Lac-Saint-Paul, Québec, Canada",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-08-05"),
		width: 1620,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage"],
	},
	{
		id: 53,
		src: photo53,
		location: "Kinadapt",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-06"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["animal"],
	},
	{
		id: 54,
		src: photo54,
		location: "Kinadapt",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-06"),
		width: 720,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait"],
	},
	{
		id: 55,
		src: photo55,
		location: "Sunrise, FL, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-14"),
		width: 1530,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["portrait", "sport"],
	},
	{
		id: 56,
		src: photo56,
		location: "Peanut Island, FL, USA",
		title: null,
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-03-14"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["paysage", "drone"],
	},
	{
		id: 57,
		src: photo57,
		location: "Montréal, Québec, Canada",
		title: "Yatai MTL",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-11"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["evenement", "drone", "urbain"],
	},
	{
		id: 58,
		src: photo58,
		location: "Montréal, Québec, Canada",
		title: "Yatai MTL",
		description: null,
		links: {
			html: null,
		},
		date: new Date("2023-06-10"),
		width: 1440,
		height: 1080,
		color: "var(--dark)",
		alt: null,
		categories: ["evenement", "animal", "portrait"],
	},
];

export { gallery };
